@description('Information about what resource is calling this Recipe. Generated by Radius.')
param context object

@description('Azure region for new resources. Defaults to the resource group location.')
param location string = resourceGroup().location

var topicName = context.resource.properties.topic
var skuName = context.resource.properties.?sku ?? 'Standard'
var namespaceName = 'sb-${uniqueString(context.resource.id, resourceGroup().id)}'

resource serviceBusNamespace 'Microsoft.ServiceBus/namespaces@2022-10-01-preview' = {
  name: namespaceName
  location: location
  sku: {
    name: skuName
    tier: skuName
  }
  tags: {
    'radius-resource': context.resource.name
    'radius-application': context.application == null ? '' : context.application.name
  }
  properties: {
    disableLocalAuth: false
    minimumTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
  }
}

resource topic 'Microsoft.ServiceBus/namespaces/topics@2022-10-01-preview' = {
  name: topicName
  parent: serviceBusNamespace
  properties: {
    enablePartitioning: false
    supportOrdering: true
  }
}

resource rootAuthorizationRule 'Microsoft.ServiceBus/namespaces/authorizationRules@2022-10-01-preview' existing = {
  name: 'RootManageSharedAccessKey'
  parent: serviceBusNamespace
}

output result object = {
  resources: [
    serviceBusNamespace.id
  ]
  values: {
    endpoint: serviceBusNamespace.properties.serviceBusEndpoint
  }
  secrets: {
    #disable-next-line outputs-should-not-contain-secrets
    connectionString: rootAuthorizationRule.listKeys().primaryConnectionString
  }
}
